<?php

use App\Enums\LoanCategory;
use App\Enums\PublishStatus;
use App\Models\Article;
use App\Models\LoanLandingPage;
use App\Models\LoanProduct;
use App\Models\Page;
use App\Models\PageSeo;

/**
 * SimpleXMLElement is not a normal iterable for collect() — collect() reads it
 * as a property bag and collapses every <url> into one key. Iterate it directly.
 *
 * @return array<int, string>
 */
function sitemapLocs(): array
{
    $xml = simplexml_load_string(test()->get('/sitemap.xml')->assertOk()->getContent());
    $locs = [];

    foreach ($xml->url as $url) {
        $locs[] = (string) $url->loc;
    }

    return $locs;
}

it('serves the sitemap as XML at the URL robots.txt advertises', function () {
    $this->get('/sitemap.xml')
        ->assertOk()
        ->assertHeader('Content-Type', 'application/xml; charset=UTF-8');

    // robots.txt is generated by RobotsController now, not a static public/ file,
    // so it advertises the app's own URL rather than a hardcoded production one.
    expect($this->get('/robots.txt')->assertOk()->getContent())
        ->toContain('Sitemap: '.route('sitemap'));
});

it('is valid, well-formed XML with a urlset root', function () {
    $xml = simplexml_load_string($this->get('/sitemap.xml')->getContent());

    expect($xml)->not->toBeFalse();
    expect($xml->getName())->toBe('urlset');
});

it('lists the core public pages', function () {
    // /about is served from its `pages` row, and is only listed while that row is live.
    Page::factory()->published()->create(['slug' => 'about']);

    expect(sitemapLocs())->toContain(
        route('home'),
        route('loans.index'),
        route('about'),
        route('contact'),
        route('quick-enquiry.show'),
        route('partners.index'),
        route('faqs.index'),
        route('resources.index'),
        route('calculators.index'),
    );
});

it('lists published loan products and excludes drafts and expired ones', function () {
    $live = LoanProduct::factory()->published()->create(['slug' => 'sitemap-live']);
    $draft = LoanProduct::factory()->create(['slug' => 'sitemap-draft', 'status' => PublishStatus::Draft]);
    $expired = LoanProduct::factory()->published()->create(['slug' => 'sitemap-expired', 'expires_at' => now()->subDay()]);

    $locs = sitemapLocs();

    expect($locs)->toContain(route('loans.show', $live));
    expect($locs)->not->toContain(route('loans.show', $draft));
    expect($locs)->not->toContain(route('loans.show', $expired));
});

/**
 * Note: LoanLandingPageController only checks the landing page's own publish
 * state, so this URL currently still renders 200 even though its parent product
 * is a draft. The sitemap deliberately does not advertise it regardless — a
 * landing page for an unpublished product is not content that should be indexed.
 */
it('omits landing pages whose parent product is unpublished', function () {
    $draftProduct = LoanProduct::factory()->create(['slug' => 'hidden-parent', 'status' => PublishStatus::Draft]);
    $landingPage = LoanLandingPage::factory()->for($draftProduct, 'loanProduct')->create([
        'slug' => 'orphan-landing',
        'status' => PublishStatus::Published,
        'published_at' => now(),
    ]);

    $url = route('loans.landing-pages.show', ['loanProduct' => $draftProduct, 'landingPage' => $landingPage]);

    expect(sitemapLocs())->not->toContain($url);
});

it('lists published articles and routed legal pages', function () {
    $article = Article::factory()->published()->create(['slug' => 'sitemap-article']);
    Page::factory()->create(['slug' => 'terms', 'status' => PublishStatus::Published, 'published_at' => now()]);

    expect(sitemapLocs())->toContain(route('resources.show', $article), route('terms'));
});

it('never exposes admin, funnel or non-routed CMS pages', function () {
    Page::factory()->create(['slug' => 'about', 'status' => PublishStatus::Published, 'published_at' => now()]);

    $locs = sitemapLocs();

    foreach ($locs as $loc) {
        expect($loc)->not->toContain('/admin');
        expect($loc)->not->toContain('/journey');
        expect($loc)->not->toContain('/applications');
        expect($loc)->not->toContain('/credit-score');
        expect($loc)->not->toContain('signature=');
    }

    // The `about` CMS row is served by AboutController at /about and listed
    // from that row exactly once — never a second time as a static entry.
    expect(collect($locs)->filter(fn (string $loc): bool => $loc === route('about')))->toHaveCount(1);
});

it('emits no duplicate URLs', function () {
    $locs = sitemapLocs();

    expect(count($locs))->toBe(count(array_unique($locs)));
});

it('only emits lastmod when the record actually tracks one', function () {
    LoanProduct::factory()->published()->create(['slug' => 'lastmod-check', 'category' => LoanCategory::PersonalLoan]);

    $xml = simplexml_load_string($this->get('/sitemap.xml')->getContent());

    $home = null;
    $product = null;

    foreach ($xml->url as $url) {
        match (true) {
            (string) $url->loc === route('home') => $home = $url,
            str_ends_with((string) $url->loc, '/loans/lastmod-check') => $product = $url,
            default => null,
        };
    }

    expect($home->lastmod->count())->toBe(0);
    expect((string) $product->lastmod)->not->toBeEmpty();
});

it('allows AI answer engines and disallows private routes in robots.txt', function () {
    $robots = $this->get('/robots.txt')->assertOk()->getContent();

    foreach (['OAI-SearchBot', 'GPTBot', 'PerplexityBot', 'Google-Extended', 'Anthropic-AI', 'Applebot-Extended', 'Bingbot'] as $bot) {
        expect($robots)->toContain("User-agent: {$bot}");
    }

    foreach (['/admin', '/login', '/register', '/api', '/journey/', '/applications/', '/credit-score/'] as $path) {
        expect($robots)->toContain("Disallow: {$path}");
    }
});

it('excludes a published record whose SEO section marks it noindex', function () {
    $listed = Article::factory()->create(['status' => PublishStatus::Published, 'published_at' => now()->subDay()]);
    $hidden = Article::factory()->create(['status' => PublishStatus::Published, 'published_at' => now()->subDay()]);
    $hidden->seoMeta()->create(['robots' => 'noindex, nofollow']);

    $locs = sitemapLocs();

    expect($locs)->toContain(route('resources.show', $listed))
        ->not->toContain(route('resources.show', $hidden));
});

it('excludes a noindex, follow record too — the directive that matters is noindex', function () {
    $article = Article::factory()->create(['status' => PublishStatus::Published, 'published_at' => now()->subDay()]);
    $article->seoMeta()->create(['robots' => 'noindex, follow']);

    expect(sitemapLocs())->not->toContain(route('resources.show', $article));
});

it('lists a record at its canonical URL when one is set', function () {
    $article = Article::factory()->create(['status' => PublishStatus::Published, 'published_at' => now()->subDay()]);
    $article->seoMeta()->create(['canonical_url' => 'https://fynnedge.com/canonical-article', 'robots' => 'index, follow']);

    $locs = sitemapLocs();

    expect($locs)->toContain('https://fynnedge.com/canonical-article')
        ->not->toContain(route('resources.show', $article));
});

it('keeps a record with an ordinary index robots value', function () {
    $article = Article::factory()->create(['status' => PublishStatus::Published, 'published_at' => now()->subDay()]);
    $article->seoMeta()->create(['robots' => 'index, follow']);

    expect(sitemapLocs())->toContain(route('resources.show', $article));
});

it('never lists the admin panel or the transactional funnel', function () {
    foreach (sitemapLocs() as $loc) {
        expect($loc)
            ->not->toContain('/admin')
            ->not->toContain('/journey/')
            ->not->toContain('/applications/')
            ->not->toContain('/credit-score/');
    }
});

it('lists about and careers only while their pages are published and indexable', function (string $slug) {
    $page = Page::factory()->published()->create(['slug' => $slug]);

    expect(sitemapLocs())->toContain(route($slug));

    $page->update(['status' => PublishStatus::Draft]);
    expect(sitemapLocs())->not->toContain(route($slug));

    $page->update(['status' => PublishStatus::Published, 'expires_at' => now()->subMinute()]);
    expect(sitemapLocs())->not->toContain(route($slug));

    $page->update(['expires_at' => null]);
    $page->seoMeta()->create(['robots' => 'noindex, follow']);
    expect(sitemapLocs())->not->toContain(route($slug));
})->with(['about', 'careers']);

it('drops a deleted about page from the sitemap', function () {
    Page::factory()->published()->create(['slug' => 'about'])->delete();

    expect(sitemapLocs())->not->toContain(route('about'));
});

it('excludes a page a Page SEO entry marks noindex', function (string $robots) {
    $pageSeo = PageSeo::factory()->create(['url_path' => '/contact']);
    $pageSeo->seoMeta()->create(['robots' => $robots]);

    expect(sitemapLocs())->not->toContain(route('contact'))
        ->toContain(route('faqs.index'));
})->with(['noindex, follow', 'noindex, nofollow']);

it('lists a page at the canonical its Page SEO entry sets', function () {
    $pageSeo = PageSeo::factory()->create(['url_path' => '/faqs']);
    $pageSeo->seoMeta()->create(['canonical_url' => 'https://fynnedge.com/help']);

    expect(sitemapLocs())->toContain('https://fynnedge.com/help')
        ->not->toContain(route('faqs.index'));
});

it('lets a Page SEO robots value win over the record, exactly as the page head does', function () {
    $terms = Page::factory()->published()->create(['slug' => 'terms']);
    $terms->seoMeta()->create(['robots' => 'index, follow']);
    PageSeo::factory()->create(['url_path' => '/terms'])->seoMeta()->create(['robots' => 'noindex, follow']);

    $this->get('/terms')->assertSee('<meta name="robots" content="noindex, follow">', false);
    expect(sitemapLocs())->not->toContain(route('terms'));
});

it('keeps the record robots when a Page SEO entry leaves robots blank', function () {
    $terms = Page::factory()->published()->create(['slug' => 'terms']);
    $terms->seoMeta()->create(['robots' => 'noindex, follow']);
    PageSeo::factory()->withMeta('/terms', 'Only The Title')->create();

    $this->get('/terms')->assertSee('<meta name="robots" content="noindex, follow">', false);
    expect(sitemapLocs())->not->toContain(route('terms'));
});

it('ignores an inactive Page SEO entry', function () {
    PageSeo::factory()->inactive()->create(['url_path' => '/contact'])->seoMeta()->create(['robots' => 'noindex, nofollow']);

    expect(sitemapLocs())->toContain(route('contact'));
});
